# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys

- type: gameMapPool
  id: SunriseMapPool
  maps:
  # НАИБОЛЕЕ ПРИОРИТЕТНЫЕ КАРТЫ
  - SunriseDelta # Прибытие стыкуется, но лишь 2 доками. Эвак стыкуется лишь 2 доками.
  #- SunriseBox # Прибытие не стыкуется, эвак стыкуется лишь 1 доком.
  #- SunriseMeta # Прибытие не стыкуется. Эвак наклоняется после стыковки.
  # МЕНЕЕ ВАЖНЫЕ:
  #- SunriseBarratry # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseFland # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseMarathon # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseBagel # Прибытие стыкуется но не туда. Эвак залазит в станцию.
  - SunrisePlasma # Прибытие стыкуется лишь 1 доком. Эвак стыкуется лишь 2 доками.
  #- SunrisePacked # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseOasis # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseConvex # Прибытие не стыкуется. Эвак залазит в станцию.
  #- SunriseLoop # Прибытие не стыкуется. Эвак залазит в станцию.
  # НЕИГРАБЕЛЬНЫЕ:
  #- SunriseReach
  #- SunriseCorvaxGelta
  #- SunriseRelic
  # SUNRISE-TODO: Старые-новые карты
  #- Glacier
  #- Shoukou
  #- Hammurabi
  #- Lighthouse
  #- Angle
  #- Pebble
  #- Ovni
  #- Kettle
  #- Tortuga
  #- Arena
